### ISSUE TITLE
Support for factions plugin tags

### ISSUE THREAD

**Issue by MrBlasyMSK** [alvin0319/GroupsAPI#11]
You could add support so that in the chat or in the nametag we can add the name of the faction or the level or the power as Purechat did.
The current Factions plugins are [FactionMaster](https://poggit.pmmp.io/p/FactionMaster/4.2.0) / [PiggyFactions](https://poggit.pmmp.io/p/PiggyFactions/2.0.2)

**Comment by alvin0319** [comment]
You can implement that by third party plugin.

I've added an API to interact with chat / nametag formats.

Please refer to [API.md](https://github.com/alvin0319/GroupsAPI/tree/master/API.md).
