### ISSUE TITLE
You can't descend someone

### ISSUE THREAD

**Issue by MrBlasyMSK** [alvin0319/GroupsAPI#12]
If you try to change someone's rank to one with lower priority it doesn't work, they stay with their current rank.

Dev13
PHP: 8.0.17
Pocketmine 4.2.6

**Comment by Xd-pro** [comment]
You need to remove their old rank with `/removegroup`

**Comment by MrBlasyMSK** [comment]
> You need to remove their old rank with `/removegroup`

thx, it work whit that
