### ISSUE TITLE
op and deop

### ISSUE THREAD

**Issue by usser1976** [alvin0319/GroupsAPI#19]
Hello, by the config Option "Whether to remove op and deop command from the PocketMine.
  # Recommend setting this to true to prevent any unwanted op/deop from being executed." kann ich false or true specify. In both cases we lock the op and deop command. :/

**Comment by alvin0319** [comment]
I don't understand what do you mean.

**Comment by usser1976** [comment]
> I don't understand what do you mean.

The plugin blocks the op and deop command.  The setting for this in the config has no effect on this.
