### ISSUE TITLE
How Get Player Rank(CODE)

### ISSUE THREAD

**Issue by johnnywai666** [alvin0319/GroupsAPI#38]
Hello, How To Get Player Rank Ah?

**Comment by alvin0319** [comment]
https://github.com/alvin0319/GroupsAPI/blob/40e4e6ded38f536cd136a3afb95fd46dbd980fee/src/alvin0319/GroupsAPI/EventListener.php#L88-#L96

**Comment by johnnywai666** [comment]
thx
